Various Layout Fixes (ASU-411)
City-of-Helsinki/asuntomyynti-react pull request #25
Opened 2021-03-15 14:02 UTC by juhakujala

- Reset apartment pagination to first page when applying new sort order
- ApartmentRow: Refactor template strucure and update styling
- ApartmentRow: Add availability options
- Fix ApartmentRow mobile breakpoint size
- Fix ProjectCard styles and remove inline styling
- ProjectCard: Fix button elements
- Add global HDS button styles
- Use correct icons for application and moving in day
- Add missing keys for pagination next/prev buttons
- ProjectCard: Define sort icon to be used with sortable fields
- Fix responsive styling for search form component
- Fix styles for search results wrapper component
- Add different info message for mobile screen sizes
- Wrap the map in a container element and fix map width for all screen sizes
- Fix z-index styles for filter dropdowns
- Fix styling for filter checkboxes
- Use unicode values for m2 and euro
- Fix filter taglist component bottom padding
- Fix incorrect translation strings and add missing ones
- Make carousel images square on screen sized between 769px and 850px
- Add initial apartment availability types
- Fix correct heading level for titles

2021-03-15 14:16 UTC, rpnykanen requested changes
Kun avaa "nyt haettavana" otsikon alla olevan asuntolistan, niin heittää erroria

![Screenshot 2021-03-15 at 16 15 33](https://user-images.githubusercontent.com/48206082/111167374-ba824980-85a9-11eb-9bc4-183efdb31b5b.png)

2021-03-15 14:46 UTC, rpnykanen reviewed
En ole ihan varma mihin tuo "nyt haettavana yhteensä 1 asuntoa" viittaa. Tuossa on screeni josta näkyy käytetyt filtterit.

![Screenshot 2021-03-15 at 16 43 21](https://user-images.githubusercontent.com/48206082/111171897-06cf8880-85ae-11eb-8153-8a1751bbc97d.png)

Kuuluisiko tuo "asunto" sana olla "huoneisto", joka on tässä asuntotuotannon kontekstissa käytetty termi asunnosta

2021-03-16 07:25 UTC, juhakujala commented
**Nyt haettavana**
Yhteensä 1 asuntoa

Tästä on tiketti vielä TODOssa, ja se tosiaan näyttää tällä hetkellä projektien lukumäärän, vaikka pitäisi näyttää asuntojen lukumäärä.
Tiketti: ASU-519

**Console error**
Tämäkin on vielä TODOssa, kun kävi ilmi, että datassa on sekä suomen että englanninkielisiä objekteja, ja se valittaa nyt duplikaateista.
Tiketti: ASU-498

2021-03-16 10:34 UTC, rpnykanen approved these changes
Ongelmat on jo noteerattu.

2021-03-16 10:34 UTC, merged